IBI.MVC/ViewModels/Messaging/Incoming/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IBI.Web.Infrastructure;

namespace IBI.Web.ViewModels.Messaging.Incoming
{
    public class FilterViewModel
    {  
            private int selectedGroupID = -1;
            

            public SelectList Groups { get; set; }
            public string BusNumber { get; set; }
            public DateTime Date { get; set; }        
            public string MessageText { get; set; }
            public string Position { get; set; }
            public string Line { get; set; }
            public string Destination { get; set; }
            public string NextStop { get; set; }
            public int GroupId
            {
                get
                {
                    return selectedGroupID;
                }
                set
                {
                    selectedGroupID = value;
                }
            }
                            
            public void Fill()
            {
                Groups = GetGroups(GroupId);                
            }

            private static SelectList GetGroups(int selectedGroupId)
            {
                return new SelectList(Common.CurrentUser.Groups(),
                                "GroupId",
                                "Description",
                                selectedGroupId);
            }
        }

             
}

IBI.MVC/ViewModels/Messaging/Incoming/ListContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MvcContrib.Pagination;
using MvcContrib.Filters;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;


namespace IBI.Web.ViewModels.Messaging.Incoming

{

    public class ListContainerViewModel
    {
        public IPagination<IBI.Shared.Models.Messages.IncomingMessage> PagedList { get; set; }
        public FilterViewModel FilterViewModel { get; set; }
        public GridSortOptions GridSortOptions { get; set; } 
    }
}

IBI.MVC/ViewModels/Messaging/Outgoing/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IBI.Web.Infrastructure;
using IBI.Web.Infrastructure.Controls;
using System.Runtime.Serialization;

namespace IBI.Web.ViewModels.Messaging.Outgoing
{
    public class FilterViewModel
    {  
            private int selectedGroupID = -1;
            //private int selectedMessageCategoryID = -1;
            
            public SelectList Groups { get; set; }
            //public SelectList MessageCategories { get; set; }
            public string BusNumber { get; set; }
            public DateTime Date { get; set; }
            public string Title { get; set; } 
            public string MessageText { get; set; } 
            public string MessageCategoryName{get;set;}
            public DateTime ValidFrom { get; set; }
            public DateTime ValidTo { get; set; }
            public string SenderName { get; set; }
            public bool ShowExpiredOnly { get; set; }
            public string SelectedMsgs { get; set; }
            public int GroupId
            {
                get
                {
                    return selectedGroupID;
                }
                set
                {
                    selectedGroupID = value;
                }
            }
            //public int MessageCategoryId
            //{
            //    get
            //    {
            //        return selectedMessageCategoryID;
            //    }
            //    set
            //    {
            //        selectedMessageCategoryID = value;
            //    }
            //}
                            
            public void Fill()
            {
                Groups = GetGroups(GroupId);
                //MessageCategories = GetMessageCategories();
            }

            private static SelectList GetGroups(int selectedGroupId)
            {
                return new SelectList(Common.CurrentUser.Groups(),
                                "GroupId",
                                "Description",
                                selectedGroupId);
            }

            //private static SelectList GetMessageCategories(int selectedMessageCategoryId)
            //{
            //    return new SelectList(Common.CurrentUser.Groups(),
            //                    "MessageCategoryId",
            //                    "CaetgoryName",
            //                    selectedMessageCategoryId);
            //}
        }

             
}

IBI.MVC/ViewModels/Messaging/Outgoing/ListContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MvcContrib.Pagination;
using MvcContrib.Filters;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;


namespace IBI.Web.ViewModels.Messaging.Outgoing

{

    public class ListContainerViewModel
    {
        public IPagination<IBI.Shared.Models.Messages.Message> PagedList { get; set; }
        public FilterViewModel FilterViewModel { get; set; }
        public GridSortOptions GridSortOptions { get; set; } 
    }
}

IBI.MVC/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using IBI.Shared.Models.Messages;
using IBI.Web.ViewModels;
using System.Web.Mvc;
using IBI.Web.Infrastructure;
using MvcContrib.UI.Grid;
using IBI.Web.ViewModels.Messaging;
using MvcContrib.Pagination;
using MvcContrib.Sorting;
using System.Globalization;
using IBI.Web.Infrastructure.CustomAttributes;

namespace IBI.Web.Controllers
{


    [AuthorizeLogin]
    public class MessageController : Controller
    {

        private const int OUTGOING_DEFAULT_VALIDITY_HOURS = 24;

        [HttpGet]
        public ActionResult List(
         string busNumber,
         string subject,
         int? messageCategoryID,
         int? customerId,
         GridSortOptions gridSortOptions,
         int? page,
         bool loadAfterSave = false)
        {

            if (page != null) //[KHI]: HACK to avoid Save Message dialog again.
                loadAfterSave = false;


            var messageList = ServiceManager.GetMessages(busNumber, customerId ?? 0);

            // Set default sort column
            if (string.IsNullOrWhiteSpace(gridSortOptions.Column))
            {
                gridSortOptions.Column = "DateModified";
                gridSortOptions.Direction = SortDirection.Descending;
            }

            // Filter on MessageCategory 
            if (messageCategoryID.HasValue)
            {
                messageList = messageList.Where(a => a.MessageCategoryId == messageCategoryID).ToList();
            }

            // Filter on subject 
            if (!(string.IsNullOrEmpty(subject)))
            {
                messageList = messageList.Where(a => a.Subject.Contains(subject)).ToList();
            }



            // Create all filter data and set current values if any
            // These values will be used to set the state of the select list and textbox
            // by sending it back to the view.
            var filterViewModel = new FilterViewModel();
            filterViewModel.CustomerId = customerId.Value;
            filterViewModel.BusNumber = busNumber;
            filterViewModel.MessageCategoryIDFilter = messageCategoryID ?? -1;
            filterViewModel.Fill();

            // Order and page the product list
            var pagedList = messageList
                .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                   .AsPagination(page ?? 1, 6);


            var listContainer = new ListContainerViewModel
            {
                PagedList = pagedList,
                FilterViewModel = filterViewModel,
                GridSortOptions = gridSortOptions,
                LoadAfterSave = loadAfterSave
            };

            return View(listContainer);
        }


        //[HttpPost]
        ////[Ajax(true)]
        //public ActionResult Edit(ViewModels.Messaging.MessageEditModel model)
        //{
        //    Message msgToEdit = model.MessageToEdit;

        //    List<String> BusNumbers = IBI.Shared.AppUtility.CommaValuesToList(model.BusNumbers);

        //    if (model.CategoryChanged == "true")
        //    {
        //        model.CategoryChanged = "";



        //        int hours = OUTGOING_DEFAULT_VALIDITY_HOURS;

        //        if (model.MessageToEdit.MessageCategoryId != null)                    
        //            hours = GetCategoryValidityTime(model.MessageToEdit.CustomerId, model.MessageToEdit.MessageCategoryId.Value);


        //        model.MessageToEdit.ValidFrom = DateTime.Now;
        //        model.MessageToEdit.ValidTo = DateTime.Now.AddHours(hours);
        //        model.MessageToEdit.Buses = BusNumbers;
        //        model.MessageCategories = ViewModels.Messaging.MessageEditModel.GetMessageCategories(msgToEdit.CustomerId, msgToEdit.MessageCategoryId);


        //        ModelState.Remove("MessageToEdit.MessageCategoryId");
        //        ModelState.Remove("MessageToEdit.Subject");
        //        ModelState.Remove("MessageToEdit.ValidFrom");
        //        ModelState.Remove("MessageToEdit.ValidTo");
        //        ModelState.Remove("MessageToEdit.MessageText");

        //        //ModelState.AddModelError("isValid", "Category Changed");

        //        return View("Edit", model);
        //    }

        //    //check Valid From / Valid To. 
        //    if (ModelState.IsValid)
        //    {
        //        if (msgToEdit.SenderId == null || msgToEdit.SenderId <= 0)
        //           msgToEdit.SenderId = UserManager.CurrentUser.UserId;

        //        msgToEdit.LastModifiedBy = UserManager.CurrentUser.UserId;

        //        msgToEdit.Buses = BusNumbers; //new List<string> { msgToEdit.DefaultBus };

        //        int msgId = ServiceManager.SaveMessage(msgToEdit);
        //        ModelState.Clear();
        //        model.PostResult = "success";
        //        //return PartialView("List", new { customerId = msgToEdit.CustomerId, busNumber = msgToEdit.BusNumber });
        //        //return RedirectToAction()

        //        return RedirectToAction("List", new { customerId = msgToEdit.CustomerId, busNumber = msgToEdit.DefaultBus, loadAfterSave = true });

        //    }

        //    model.MessageCategories = ViewModels.Messaging.MessageEditModel.GetMessageCategories(msgToEdit.CustomerId, msgToEdit.MessageCategoryId);
        //    model.MessageToEdit.Buses = BusNumbers;

        //    return View("Edit", model);
        //}

        //[HttpGet]
        ////[Ajax(true)]
        //public ActionResult Edit(int customerId, string busNumber, int id = 0){

        //    ViewModels.Messaging.MessageEditModel model = new ViewModels.Messaging.MessageEditModel(customerId, id);

        //    if (id == 0)//new message
        //    {
        //        model.MessageToEdit.DefaultBus = busNumber;
        //        model.MessageToEdit.CustomerId = customerId;
        //        model.MessageToEdit.Buses = new List<string> { busNumber };
        //        model.MessageToEdit.ValidFrom = DateTime.Now;
        //        model.MessageToEdit.ValidTo = DateTime.Now.AddDays(1);
        //    }
        //    else //edit message
        //    {
        //        model.MessageToEdit.DefaultBus = busNumber;
        //    }

        //    return View("Edit", model); 

        //}

        private MessageEditModel HtmlDecode(MessageEditModel model)
        {
            model.MessageToEdit.Subject = WebUtility.HtmlDecode(model.MessageToEdit.Subject);
            model.MessageToEdit.MessageText = WebUtility.HtmlDecode(model.MessageToEdit.MessageText);
            return model;
        }

        private MessageEditModel HtmlEncode(MessageEditModel model)
        {
            model.MessageToEdit.Subject = WebUtility.HtmlEncode(model.MessageToEdit.Subject);
            model.MessageToEdit.MessageText = WebUtility.HtmlEncode(model.MessageToEdit.MessageText);
            return model;
        }

        public string TellMeDate()
        {
            return DateTime.Today.ToString();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public String GetCategoryValue(string categoryId, DateTime validFrom)
        {
            MessageCategory category = ViewModels.Messaging.MessageEditModel.GetCategory(int.Parse(categoryId));
            if (category != null)
            {
                DateTime validTo = CalculateValidTo(validFrom, category);
            }
            return "";
        }
        [HttpPost]
        [ValidateInput(false)]
        //[Ajax(true)]
        public ActionResult AddEdit(ViewModels.Messaging.MessageEditModel model)
        {
            //Encode the values
            model = HtmlEncode(model);
            Message msgToEdit = model.MessageToEdit;


            List<String> BusNumbers = IBI.Shared.AppUtility.CommaValuesToList(model.BusNumbers);


            if (model.CustomerChanged == "true")
            {
                model.CustomerChanged = "";
                model.MessageToEdit.CustomerId = model.CustomerId;
                model.CustomerList = ViewModels.Messaging.MessageEditModel.GetCustomers(msgToEdit.CustomerId);
                model.MessageCategories = ViewModels.Messaging.MessageEditModel.GetMessageCategories(msgToEdit.CustomerId, 0);

                model.MessageReplyType = ViewModels.Messaging.MessageEditModel.GetMessageReplyType(msgToEdit.MessageReplyTypeId);
                model.MessageToEdit.MessageReplyTypeId = null;

                model.MessageToEdit.MessageCategoryId = null;
                model.BusNumbers = "";
                model.MessageToEdit.MessageText = "";
                model.MessageToEdit.Subject = "";
                model.MessageToEdit.ValidFrom = DateTime.MinValue;
                //model.MessageToEdit.ValidTo = DateTime.MinValue;

                ModelState.Remove("MessageToEdit.MessageCategoryId");
                ModelState.Remove("MessageToEdit.Subject");
                ModelState.Remove("MessageToEdit.ValidFrom");
                ModelState.Remove("MessageToEdit.ValidTo");
                ModelState.Remove("MessageToEdit.MessageText");
                ModelState.Remove("CustomerId");

                if (model.CustomerId > 0)
                    model.FormStatus = "1";
                else
                    model.FormStatus = "0";

                model = HtmlDecode(model);
                Infrastructure.CacheManager.Store("CurrentPageCustomerId", msgToEdit.CustomerId);
                return View("AddEdit", model);
            }


            if (model.CategoryChanged == "true")
            {
                model.CategoryChanged = "";
                model.MessageToEdit.CustomerId = model.CustomerId;

                if (model.MessageToEdit.ValidFrom == DateTime.MinValue)
                {
                    model.MessageToEdit.ValidFrom = DateTime.Now;
                }

                int hours = OUTGOING_DEFAULT_VALIDITY_HOURS;

IBI.MVC/Views/Message/Administration.cshtml
@{
    ViewBag.Title = "Administration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Administration</h2>

IBI.MVC/Views/Message/Archive.cshtml
@{
    ViewBag.Title = "Archive";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Archive</h2>

IBI.MVC/Views/Message/Incoming.cshtml
@model IBI.Web.ViewModels.Messaging.Incoming.ListContainerViewModel
 
@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid
@using IBI.Web.Common

@{
    ViewBag.Title = "Incoming Messages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head{
 
    <link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />    
    <link href="@Url.Content("~/Scripts/custom-datetime/txtdropdown.css")" rel="stylesheet" type="text/css" /> 

    <script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script> 

    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" />

}
 

    @{
        MvcContrib.Pagination.IPagination<IBI.Shared.Models.Messages.IncomingMessage> PagedList = Model.PagedList;
        IBI.Web.ViewModels.Messaging.Incoming.FilterViewModel FilterViewModel = Model.FilterViewModel;
        MvcContrib.UI.Grid.GridSortOptions GridSortOptions = Model.GridSortOptions;               
     } 

 <!-- Search Filters - Start -->  

 <script type="text/javascript">

     $(document).ready(function () {
      
         $(".mydatepicker").val("@((FilterViewModel.Date==null || FilterViewModel.Date==DateTime.MinValue) ? "" : FilterViewModel.Date.ToShortDateString())");
         
     });

    </script>  
       

   @{
       var htmlAttributes = new Dictionary<string, object> { { "data-autopostback", "true" } }; 
    }    
    <!--new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "BusStatusLogGrid" }))-->

   @{Html.EnableClientValidation(true);}
   @using (Html.BeginForm("Incoming", "Message", FormMethod.Post, new { onsubmit = "beginHtmlSubmit()" }))
   {
    <div class="input-table grey-box" style="width:99%">
        <table cellspacing="5" width="100%">
            <tr>
                
                <td>
                    <label class="block">Group</label>
                     @Html.DropDownList("groupId", FilterViewModel.Groups, "-- All --")
                    <br />
                </td>
                
                <td>
                    <label class="block">Bus Number</label>
                    @Html.TextBox("busNumber", FilterViewModel.BusNumber, new { @class = "short", maxlength = "5" })
                    <br />
                    @Html.ValidationMessageFor(model => model.FilterViewModel.BusNumber)
                </td>
                 <td>
                    <label class="block">Date</label>
                    @Html.EditorFor(model => model.FilterViewModel.Date, "", "date")
                    <br />
                    @Html.ValidationMessageFor(model => model.FilterViewModel.Date)
                </td>
                <td>
                    <label class="block">Message</label>
                    @Html.TextBox("messageText", FilterViewModel.MessageText, new { @class = "short" })
                    <br />
                </td>
                
                <td>
                    <label class="block">Position</label>
                    @Html.TextBox("Position", FilterViewModel.Line, new { @class = "short", size = 10 })
                    <br />
                </td>

                <td>
                    <label class="block">Line</label>
                    @Html.TextBox("line", FilterViewModel.Line, new { @class = "short", size = 10 })
                    <br />
                </td>

                <td>
                    <label class="block">Destination</label>
                    @Html.TextBox("destination", FilterViewModel.Destination, new { @class = "short", size = 10 })
                    <br />
                </td>
                
                <td>
                    <label class="block">Next Stop</label>
                    @Html.TextBox("nextStop", FilterViewModel.NextStop, new { @class = "short", size = 10 })
                    <br />
                </td>
                
                <td valign="bottom">     
                    <input type="submit" value="Search" style="margin-top: 30px;"  />
                </td>
            </tr>
        </table> 
       
    </div>
   }
    <!-- Search Filters - End --> 


    
    <!-- Searched Results - start -->   

    @{
        var grid = Html.Grid(Model.PagedList)
                    .Columns(
                        column=>{ 
                            column.For(c => c.BusGroupName).Named("Group");
                            column.For(c => c.BusNumber).Named("Bus Number");  
                            column.For(c => c.DateAdded).Named("Timestamp").Format("{0:dd/MM/yyyy HH:mm}");
                            column.For(c => c.MessageText).Named("Message");
                            column.Custom(c => IBI.Web.Common.WebUtil.GetFormattedGPS(c.Latitude, c.Longitude)).Named("Position");
                            column.For(c => c.Line).Named("Line"); 
                            column.For(c => c.Destination).Named("Destination");
                            column.For(c => c.NextStop).Named("Next Stop");
                            }                        
                    )
                    .Sort(Model.GridSortOptions)
                    .Attributes(@class => "table-list");

     }

     @{
         if (Model.PagedList !=null && Model.PagedList.Count() > 0)
         { 
           @* <span style="float:right; display:inline-block; margin-bottom:5px;">
                 <a href="javascript:void(0)" onclick="SelectText('searchedResults')">Select All</a>
            </span>*@
        
            <div id="searchedResults">
                @grid 
            </div>
             
         Html.RenderPartial("Pager", PagedList);  
         }
         else 
         {
             <div class="no-data">There are no incoming messages available</div> 
         }
      }
       
    <!-- Searched Results - end -->   

IBI.MVC/Views/Message/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        
    </div>
</body>
</html>

IBI.MVC/Views/Message/IndexList.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<head>
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />
</head>

<body style="margin:0px">

<div class="box" style="height:96%">
<iframe id="frmMain" width="100%" height="100%" scrolling="no" frameborder="0" marginwidth="0" marginheight="0" src="@Url.Action("List", "Message", new{customerId = ViewData["customerId"], busNumber = ViewData["busNumber"]})" />    
</div>
</body>

@*@Url.Action("List", "Message", new{customerId = ViewData["customerId"], busNumber = ViewData["busNumber"]})*@

IBI.MVC/Views/Message/IndexNew.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}


<head>
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />
</head>

<body style="margin:0px">

<div class="box" style="height: 96%">
<iframe id="frmMain" width="100%" height="100%" scrolling="no"  frameborder="0" marginwidth="0" marginheight="0" style="overflow:hidden;" src="@Url.Action("Edit", "Message", new{customerId = ViewData["customerId"], busNumber = ViewData["busNumber"], id = ViewData["messageId"]})" />     
</div>
</body>
  @*@Url.Action("Edit", "Message", new{customerId = ViewData["customerId"], busNumber = ViewData["busNumber"]})*@

IBI.MVC/Views/Message/List.cshtml
@*@model IBI.Web.ViewModels.Messaging.MessageListModel*@
@model IBI.Web.ViewModels.Messaging.ListContainerViewModel

@using MvcContrib.Pagination
@using MvcContrib.Sorting
@using MvcContrib.UI
@using MvcContrib.UI.Grid

@{
    Layout = "~/Views/Shared/_Popup.cshtml";    
}
 
@section Head{
    
    <!--jAlert-->
    <script src="@Url.Content("~/Scripts/plugins/jAlert/jquery.alert.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Scripts/plugins/jAlert/jquery.alert.css")" rel="stylesheet" type="text/css" />
 
 
    <script>
         $(document).ready(function () {

             var loadedAfterSave = '@Model.LoadAfterSave';
             if (loadedAfterSave == 'True') {
                 //alert('Message Saved Successfully');
                 jAlert("Message saved successfully", "Success!!!", null);
             }
 
         });  
    </script> 
}

@section Popup{


<div id="MsgGrid" style="padding: 7px;">
       
    @{
        MvcContrib.Pagination.IPagination<IBI.Shared.Models.Messages.Message> PagedList = Model.PagedList;
        IBI.Web.ViewModels.Messaging.FilterViewModel FilterViewModel = Model.FilterViewModel;
        MvcContrib.UI.Grid.GridSortOptions GridSortOptions = Model.GridSortOptions;               
     } 
      

   <!-- Search Filters - Start -->    
   

   @using (Ajax.BeginForm("List", "Message", new { }, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "MsgGrid", OnBegin = "beginAjaxSubmit" }))
   {
    <div class="input-table grey-box">
        <table>
            <tr valign="bottom">
                <td class="label">Title</td>
                <td>
                    @Html.TextBox("subject", FilterViewModel.MessageSubjectFilter, new { size = 20, maxlength = "100" })
                </td>
                <td class="label">
                    Category
                </td>
                <td>                   
                    @Html.DropDownList("messageCategoryId", FilterViewModel.MessageCategories, "-- All --", null)
                </td>
                <td style="vertical-align: top;">
                    <input type="hidden"  name="customerId" value="@FilterViewModel.CustomerId" />
                    <input type="hidden"  name="busNumber"  value="@FilterViewModel.BusNumber" />
                    <input type="hidden"  name="loadAfterSave"  value="False" />
                    
                    <input type="submit" value="Search" />
                </td>
            </tr>
        </table> 
    </div>
   }
    <!-- Search Filters - End --> 
 
    <!-- Searched Results - start -->   
    @{
        var grid = Html.Grid(PagedList)
        .Columns(column =>
        {
         column.For(a => a.CategoryName);
         column.Custom(x => IBI.Shared.AppUtility.TrimText(x.Subject, 10)).Named("Title");
         column.Custom(x => IBI.Shared.AppUtility.TrimText(x.MessageText, 30)).Named("Message Text");
         column.For(a => a.ValidFrom).Encode(false).Format("{0:dd/MM/yyyy HH:mm}");
         column.For(a => a.ValidTo).Encode(false).Format("{0:dd/MM/yyyy HH:mm}");
         column.For(a => a.SenderName).Named("Sender");
         column.Custom(a => Html.ActionLink("Edit", "AddEdit", "Message", new { customerId = a.CustomerId, busNumber = @FilterViewModel.BusNumber, messageid = a.MessageId }, new { target = "_top" })).Encode(false).Attributes(@class => "link");
        
            //column.For(a => @Html.ActionLink("Edit", "AddEdit", "Message", new { customerId = a.CustomerId, busNumber = @FilterViewModel.BusNumber, id = a.MessageId }, new { target = "_top" })).Encode(false).Attributes(@class => "link");
            
     })
     .Sort(Model.GridSortOptions)
     .Attributes(@class=>"table-list");
     
    }

   @{
       if (Model.PagedList.Count() > 0)
       { 
            @grid
       }
       else
       {
             <div class="no-data">There are no messages available</div> 
       }
    }
    <!-- Searched Results - start -->   
    <br /><br />
    <!-- Page - start -->
    @{ 
        Html.RenderPartial("Pager", PagedList);  
    }
    <!-- Page - end -->

    </div>    
     

}

IBI.MVC/Views/Message/PartialDisplayedConfirmations.cshtml
@model  List<IBI.Shared.Models.Messages.MessageDisplayConfirmations>
<script type="text/javascript">
    $(document).ready(function () {
            $('.tbDisplayConfirmationsAndReplies').tablesorter({
                widgets: ['zebra', 'columns'],
                usNumberFormat: false,
                sortReset: true,
                sortRestart: true
            });
    });
</script>

<label style="font-size: 12px;font-weight: bolder;color: #555;vertical-align: text-bottom;text-align: left;position: relative;top: 4px;">Display Confirmations</label> 
<table class="tbDisplayConfirmationsAndReplies" border="0" style="border-collapse: collapse;width:100%;text-align:left;">
    @{
        if (Model != null && Model.Count > 0)
        { 
            <thead>
                <tr >
			        <th style="border-collapse: collapse;padding: 5px; text-align: left; background-color:#dedede;"> 
                        BusNumber
			        </th>
                    <th style="border-collapse: collapse;padding: 5px; text-align: left; background-color:#dedede;"> 
                        Group
			        </th>
   			        <th style="border-collapse: collapse;padding: 5px; text-align: left; background-color:#dedede;"> 
                       Confirmation at
			        </th>
		        </tr>
            </thead>
            @Html.Raw("<tbody>");
            int i = 1;
            foreach (IBI.Shared.Models.Messages.MessageDisplayConfirmations msg in Model)   
            {
                <tr class='@( (i%2==0) ? "even": "odd" )'>
			        <td style="border-collapse: collapse;padding: 5px; text-align: left;"> 
                        @Html.Raw(msg.BusNumber)
			        </td>
                    <td style="border-collapse: collapse;padding: 5px; text-align: left;"> 
                        @Html.Raw(msg.BusGroupName)
			        </td>

   			        <td style="border-collapse: collapse;padding: 5px; text-align: left;"> 
                       @Html.Raw(msg.DisplayTime.ToString(IBI.Web.Common.Settings.DateTimeFormat))
			        </td>
		        </tr>
                
                i++;
            }
            @Html.Raw("</tbody>");
        }
    }
</table>