IBI.MVC/ViewModels/BusEventLog/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IBI.Web.Infrastructure;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace IBI.Web.ViewModels.BusEventLog
{
    public class FilterViewModel
    {   
         
            [DataMember]
            [Required(ErrorMessage = "Bus number required")]
            public string BusNumber { get; set; }

            [DataMember]
            [Required(ErrorMessage = "Date is required")]
            public DateTime? Date { get; set; }
                            
            public void Fill()
            {
                 //do nothing yet
            }

            
        }

             
}

IBI.MVC/ViewModels/BusEventLog/ListContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MvcContrib.Pagination;
using MvcContrib.Filters;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;


namespace IBI.Web.ViewModels.BusEventLog

{

    public class ListContainerViewModel
    {
        public IPagination<IBI.Shared.Models.BusTree.BusEventLog> PagedList { get; set; }
        public FilterViewModel FilterViewModel { get; set; }
        public GridSortOptions GridSortOptions { get; set; }
    }
}

IBI.MVC/Controllers/BusEventLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcContrib.Pagination;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using IBI.Web.Infrastructure;
using IBI.Web.ViewModels.BusEventLog; 
using System.Globalization;
using IBI.Web.Infrastructure.CustomAttributes;

namespace IBI.Web.Controllers
{ 
    [AuthorizeLogin]
    public class BusEventLogController : Controller
    {        
        public ActionResult Index(
            string busNumber,
            DateTime? date,
            GridSortOptions gridSortOptions,
            int? page)
        {
             
            if (date == null || busNumber == "")
            {
                ListContainerViewModel emptyModel = new ListContainerViewModel();
                FilterViewModel filters = new FilterViewModel();
                filters.BusNumber = "";
                filters.Date = date ?? DateTime.Now;
                emptyModel.FilterViewModel = filters;

                var pagedListx = new List<IBI.Shared.Models.BusTree.BusEventLog>()
                    .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                    .AsPagination(page ?? 1, 100);


                emptyModel.PagedList = pagedListx;
                return View(emptyModel);
            }


            //try
            //{
            //    date = DateTime.ParseExact(dateFrom, "dd-MM-yyyy", CultureInfo.InvariantCulture);
            //}
            //catch (Exception ex)
            //{
            //    return RedirectToAction("BusTree", "Bus", new { errorMessage = "date=" + dateFrom + " - " + ex.Message });
            //}

                //Response.Write(date.ToString());

                //Response.End();


            //return RedirectToAction("BusTree", "Bus", new { errorMessage = "No error" });
            var list = ServiceManager.GetBusEventLog(busNumber, date.Value);

            //Response.Write(list.Count());

            //Response.End();

            // Set default sort column
            if (string.IsNullOrWhiteSpace(gridSortOptions.Column))
            {
                gridSortOptions.Column = "TimeStamp";
                gridSortOptions.Direction = SortDirection.Descending;
            }


            // Filter on subject 
            if (busNumber != null && date != null)
            {
                list = list.Where(a => a.BusNumber == busNumber).ToList();
            }


            // Create all filter data and set current values if any
            // These values will be used to set the state of the select list and textbox
            // by sending it back to the view.
            var filterViewModel = new FilterViewModel();
            filterViewModel.BusNumber = busNumber;
            filterViewModel.Date = date;
            filterViewModel.Fill();

            // Order and page the product list
            var pagedList = list
                .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                   .AsPagination(page ?? 1, 10000);


            var listContainer = new ListContainerViewModel
            {
                PagedList = pagedList,
                FilterViewModel = filterViewModel,
                GridSortOptions = gridSortOptions
            };

            return View(listContainer);

            return null;
        }

    }
}

IBI.MVC/Views/BusEventLog/Index.cshtml
@model IBI.Web.ViewModels.BusEventLog.ListContainerViewModel


@using MvcContrib.Pagination
 

@{
    ViewBag.Title = "Mermaid IBI - Bus Logs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head{
    
   <script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script> 
     
    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" /> 
    <link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />  
}



<h2>Bus Event Logs</h2>
  

<div id="BusStatusLogGrid">


    @{
        MvcContrib.Pagination.IPagination<IBI.Shared.Models.BusTree.BusEventLog> PagedList = Model.PagedList;
        IBI.Web.ViewModels.BusEventLog.FilterViewModel FilterViewModel = Model.FilterViewModel;
        MvcContrib.UI.Grid.GridSortOptions GridSortOptions = Model.GridSortOptions;               
     } 
       
    
    @{
        Html.RenderPartial("SearchFilters", FilterViewModel);
        <br /> 
        Html.RenderPartial("SearchResults", Model); 
          
        <br />
        Html.RenderPartial("Pager", PagedList);  
    } 

</div>       
 

IBI.MVC/Views/BusEventLog/SearchFilters.cshtml
@model IBI.Web.ViewModels.BusEventLog.FilterViewModel
@using IBI.Web.Common

 <!-- Search Filters - Start --> 
 
 <link href="@Url.Content("~/Scripts/custom-datetime/txtdropdown.css")" rel="stylesheet" type="text/css" /> 
   
   
   @{
       var htmlAttributes = new Dictionary<string, object> { { "data-autopostback", "true" } }; 
    }    
    <!--new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "BusStatusLogGrid" }))-->

   @{Html.EnableClientValidation(true);}
   @using (Html.BeginForm("Index", "BusEventLog", FormMethod.Get, new { onsubmit = "beginHtmlSubmit()" }))
   {
    <div class="input-table grey-box" style="width:99%">
        <table cellspacing="5">
            <tr>
                <td>
                    <label>Bus Number</label>
                    @Html.TextBoxFor(model => model.BusNumber, new { @class = "short", size = 4, maxlength = "20" })
                    <br />
                    @Html.ValidationMessageFor(model => model.BusNumber)
                </td>
                 <td>
                    <label>Date</label>
                    @Html.EditorFor(model => model.Date)
                    <br />
                    @Html.ValidationMessageFor(model => model.Date)
                </td>
                <td>    
                    <input type="submit" value="Search"  />
                </td>
            </tr>
        </table> 
       
    </div>
   }
    <!-- Search Filters - End --> 
 

IBI.MVC/Views/BusEventLog/SearchResults.cshtml
@model IBI.Web.ViewModels.BusEventLog.ListContainerViewModel

@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid

@{
    Layout = null;
}

<!-- Searched Results - start -->   
    @{
        var grid = Html.Grid(Model.PagedList)
                    .Columns(
                        column=>{
                            column.For(c => c.TimeStamp).Named("Timestamp").Format("{0:" + @IBI.Web.Common.Settings.DateTimeFormat + "}");
                            column.For(c=>c.BusNumber).Named("Bus#");
                            column.For(c => c.ClientType).Named("Client");                            
                            column.For(c => c.Line).Named("Line");
                            column.For(c => c.From).Named("From");
                            column.For(c => c.Destination).Named("Destination");
                            column.For(c => c.IsMaster).Named("Master");
                            column.For(c => c.IsOverwritten).Named("Overwritten");
                            column.For(c => c.JourneyNumber).Named("Journey#");
                            column.For(c => c.StopNumber).Named("Stop#");
                            column.For(c => c.Source).Named("Source");
                            column.For(c => c.Result).Named("Result");
                            column.For(c => c.EventId).Named("Event");
                            column.For(c => c.EventSource).Named("Event Src.");
                            column.For(c => c.EventData).Named("Event Data");
                            column.For(c => c.Zone).Named("Zone");
                            //column.For(c => c.GPS1).Named("GPS1");
                            //column.For(c => c.GPS2).Named("GPS2");
                            column.For(c => c.ExtraData).Named("Ext. Data");
                            }                        
                    )
                    .Sort(Model.GridSortOptions)
                    .Attributes(@class => "table-list");

     }

     @{
         if (Model.PagedList !=null && Model.PagedList.Count() > 0)
         { 
            <span style="float:right; display:inline-block; margin-bottom:5px;">
                 <a href="javascript:void(0)" onclick="SelectText('searchedResults')">Select All</a>
            </span>
        
            <div id="searchedResults">
                @grid 
            </div>
         }
         else 
         {
             <div class="no-data">There are no logs available</div> 
         }
      }

       
    <!-- Searched Results - end -->   